package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Bitacora generated by hbm2java
 */
public class Bitacora  implements java.io.Serializable {


     private Integer idBitacora;
     private Integer idUsuario;
     private Integer idServicio;
     private Integer idEmpresa;
     private String descripcion;
     private Date fecha;
     private String tipo;

    public Bitacora() {
    }

	
    public Bitacora(String descripcion, Date fecha, String tipo) {
        this.descripcion = descripcion;
        this.fecha = fecha;
        this.tipo = tipo;
    }
    public Bitacora(Integer idUsuario, Integer idServicio, Integer idEmpresa, String descripcion, Date fecha, String tipo) {
       this.idUsuario = idUsuario;
       this.idServicio = idServicio;
       this.idEmpresa = idEmpresa;
       this.descripcion = descripcion;
       this.fecha = fecha;
       this.tipo = tipo;
    }
   
    public Integer getIdBitacora() {
        return this.idBitacora;
    }
    
    public void setIdBitacora(Integer idBitacora) {
        this.idBitacora = idBitacora;
    }
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Integer getIdServicio() {
        return this.idServicio;
    }
    
    public void setIdServicio(Integer idServicio) {
        this.idServicio = idServicio;
    }
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


