package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

/**
 * CfdisRecibidos generated by hbm2java
 */
public class CfdisRecibidos implements java.io.Serializable {

    private Integer idCfdiRecibido;
    private int idSocioComercial;
    private int idEmpresa;
    private Integer idOrdenCompra;
    private String serie;
    private Long folio;
    private String uuid;
    private Date fecha;
    private BigDecimal total;
    private String xmlSat;
    private Date fechaRecepcion;
    private String estado;
    private String error;
    private Boolean reportado;
    private String estadoNotificacion;
    private String nombreArchivo;
    private byte[] pdf;
    private Boolean statusPdf;
    private Boolean esCfd;
    private Boolean reportadoXsa;
    private BigDecimal totalOc;
    private String tipoMoneda;
    private BigDecimal tipoCambio;
    private String entradaAlmacen;
    private String controlCalidad;
    private String autorizacion;
    private String tiposWarn;

    public CfdisRecibidos() {
    }

    public CfdisRecibidos(Integer idCfdiRecibido, int idSocioComercial, String serie, Long folio, Date fecha, Date fechaRecepcion, String estado, String tiposWarn) {
        this.idCfdiRecibido = idCfdiRecibido;
        this.idSocioComercial = idSocioComercial;
        this.serie = serie;
        this.folio = folio;
        this.fecha = fecha;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
        this.tiposWarn = tiposWarn;
    }

    public CfdisRecibidos(Integer idCfdiRecibido, int idSocioComercial, String serie, Long folio, String uuid, Date fecha, BigDecimal total, Date fechaRecepcion, String estado, String error, BigDecimal totalOc, String tipoMoneda, BigDecimal tipoCambio, String entradaAlmacen, String controlCalidad, String autorizacion, String tiposWarn) {
        this.idCfdiRecibido = idCfdiRecibido;
        this.idSocioComercial = idSocioComercial;
        this.serie = serie;
        this.folio = folio;
        this.uuid = uuid;
        this.fecha = fecha;
        this.total = total;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
        this.error = error;
        this.totalOc = totalOc;
        this.tipoMoneda = tipoMoneda;
        this.tipoCambio = tipoCambio;
        this.entradaAlmacen = entradaAlmacen;
        this.controlCalidad = controlCalidad;
        this.autorizacion = autorizacion;
        this.tiposWarn = tiposWarn;
    }

    public CfdisRecibidos(Integer idCfdiRecibido, int idSocioComercial, String serie, Long folio, Date fecha, BigDecimal total, Date fechaRecepcion, String estado, String tiposWarn) {
        this.idCfdiRecibido = idCfdiRecibido;
        this.idSocioComercial = idSocioComercial;
        this.serie = serie;
        this.folio = folio;
        this.fecha = fecha;
        this.total = total;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
        this.tiposWarn = tiposWarn;
    }

    public CfdisRecibidos(int idSocioComercial, int idEmpresa, Date fecha, BigDecimal total, String xmlSat, Date fechaRecepcion, String estado) {
        this.idSocioComercial = idSocioComercial;
        this.idEmpresa = idEmpresa;
        this.fecha = fecha;
        this.total = total;
        this.xmlSat = xmlSat;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
    }

    public CfdisRecibidos(int idSocioComercial, int idEmpresa, Integer idOrdenCompra, String serie, Long folio, String uuid, Date fecha, BigDecimal total, String xmlSat, Date fechaRecepcion, String estado, String error, Boolean reportado, String estadoNotificacion, String nombreArchivo, byte[] pdf, Boolean statusPdf, Boolean esCfd, Boolean reportadoXsa, BigDecimal totalOc, String tipoMoneda, BigDecimal tipoCambio, String entradaAlmacen, String controlCalidad, String autorizacion, String tiposWarn) {
        this.idSocioComercial = idSocioComercial;
        this.idEmpresa = idEmpresa;
        this.idOrdenCompra = idOrdenCompra;
        this.serie = serie;
        this.folio = folio;
        this.uuid = uuid;
        this.fecha = fecha;
        this.total = total;
        this.xmlSat = xmlSat;
        this.fechaRecepcion = fechaRecepcion;
        this.estado = estado;
        this.error = error;
        this.reportado = reportado;
        this.estadoNotificacion = estadoNotificacion;
        this.nombreArchivo = nombreArchivo;
        this.pdf = pdf;
        this.statusPdf = statusPdf;
        this.esCfd = esCfd;
        this.reportadoXsa = reportadoXsa;
        this.totalOc = totalOc;
        this.tipoMoneda = tipoMoneda;
        this.tipoCambio = tipoCambio;
        this.entradaAlmacen = entradaAlmacen;
        this.controlCalidad = controlCalidad;
        this.autorizacion = autorizacion;
        this.tiposWarn = tiposWarn;
    }

    public Integer getIdCfdiRecibido() {
        return this.idCfdiRecibido;
    }

    public void setIdCfdiRecibido(Integer idCfdiRecibido) {
        this.idCfdiRecibido = idCfdiRecibido;
    }

    public int getIdSocioComercial() {
        return this.idSocioComercial;
    }

    public void setIdSocioComercial(int idSocioComercial) {
        this.idSocioComercial = idSocioComercial;
    }

    public int getIdEmpresa() {
        return this.idEmpresa;
    }

    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    public Integer getIdOrdenCompra() {
        return this.idOrdenCompra;
    }

    public void setIdOrdenCompra(Integer idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }

    public String getSerie() {
        return this.serie;
    }

    public void setSerie(String serie) {
        this.serie = serie;
    }

    public Long getFolio() {
        return this.folio;
    }

    public void setFolio(Long folio) {
        this.folio = folio;
    }

    public String getUuid() {
        return this.uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public Date getFecha() {
        return this.fecha;
    }

    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getXmlSat() {
        return this.xmlSat;
    }

    public void setXmlSat(String xmlSat) {
        this.xmlSat = xmlSat;
    }

    public Date getFechaRecepcion() {
        return this.fechaRecepcion;
    }

    public void setFechaRecepcion(Date fechaRecepcion) {
        this.fechaRecepcion = fechaRecepcion;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public String getError() {
        return this.error;
    }

    public void setError(String error) {
        this.error = error;
    }

    public Boolean getReportado() {
        return this.reportado;
    }

    public void setReportado(Boolean reportado) {
        this.reportado = reportado;
    }

    public String getEstadoNotificacion() {
        return this.estadoNotificacion;
    }

    public void setEstadoNotificacion(String estadoNotificacion) {
        this.estadoNotificacion = estadoNotificacion;
    }

    public String getNombreArchivo() {
        return this.nombreArchivo;
    }

    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    public byte[] getPdf() {
        return this.pdf;
    }

    public void setPdf(byte[] pdf) {
        this.pdf = pdf;
    }

    public Boolean getStatusPdf() {
        return this.statusPdf;
    }

    public void setStatusPdf(Boolean statusPdf) {
        this.statusPdf = statusPdf;
    }

    public Boolean getEsCfd() {
        return this.esCfd;
    }

    public void setEsCfd(Boolean esCfd) {
        this.esCfd = esCfd;
    }

    public Boolean getReportadoXsa() {
        return this.reportadoXsa;
    }

    public void setReportadoXsa(Boolean reportadoXsa) {
        this.reportadoXsa = reportadoXsa;
    }

    public BigDecimal getTotalOc() {
        return this.totalOc;
    }

    public void setTotalOc(BigDecimal totalOc) {
        this.totalOc = totalOc;
    }

    public String getTipoMoneda() {
        return this.tipoMoneda;
    }

    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    public String getEntradaAlmacen() {
        return this.entradaAlmacen;
    }

    public void setEntradaAlmacen(String entradaAlmacen) {
        this.entradaAlmacen = entradaAlmacen;
    }

    public String getControlCalidad() {
        return this.controlCalidad;
    }

    public void setControlCalidad(String controlCalidad) {
        this.controlCalidad = controlCalidad;
    }

    public String getAutorizacion() {
        return this.autorizacion;
    }

    public void setAutorizacion(String autorizacion) {
        this.autorizacion = autorizacion;
    }

    public String getTiposWarn() {
        return this.tiposWarn;
    }

    public void setTiposWarn(String tiposWarn) {
        this.tiposWarn = tiposWarn;
    }

}
