package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1



/**
 * ConectorAdaptador generated by hbm2java
 */
public class ConectorAdaptador  implements java.io.Serializable {


     private Integer idConectorAdaptador;
     private int idEmpresa;
     private String nombre;
     private String descripcion;
     private String conector;
     private String adaptador;

    public ConectorAdaptador() {
    }

	
    public ConectorAdaptador(int idEmpresa, String nombre) {
        this.idEmpresa = idEmpresa;
        this.nombre = nombre;
    }
    public ConectorAdaptador(int idEmpresa, String nombre, String descripcion, String conector, String adaptador) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.conector = conector;
       this.adaptador = adaptador;
    }
   
    public Integer getIdConectorAdaptador() {
        return this.idConectorAdaptador;
    }
    
    public void setIdConectorAdaptador(Integer idConectorAdaptador) {
        this.idConectorAdaptador = idConectorAdaptador;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getConector() {
        return this.conector;
    }
    
    public void setConector(String conector) {
        this.conector = conector;
    }
    public String getAdaptador() {
        return this.adaptador;
    }
    
    public void setAdaptador(String adaptador) {
        this.adaptador = adaptador;
    }




}


