package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * OrdenesCompra generated by hbm2java
 */
public class OrdenesCompra implements java.io.Serializable {

    private Integer idOrdenCompra;
    private int idEmpresa;
    private Integer idSocioComercial;
    private String numeroOc;
    private BigDecimal total;
    private String tipoMoneda;
    private BigDecimal tipoCambio;
    private String rfcVendedor;

    public OrdenesCompra() {
    }

    public OrdenesCompra(Integer idOrdenCompra, String numeroOc) {
        this.idOrdenCompra = idOrdenCompra;
        this.numeroOc = numeroOc;
    }

    public OrdenesCompra(int idEmpresa, String numeroOc, BigDecimal total, String rfcVendedor) {
        this.idEmpresa = idEmpresa;
        this.numeroOc = numeroOc;
        this.total = total;
        this.rfcVendedor = rfcVendedor;
    }

    public OrdenesCompra(int idEmpresa, Integer idSocioComercial, String numeroOc, BigDecimal total, String tipoMoneda, BigDecimal tipoCambio, String rfcVendedor) {
        this.idEmpresa = idEmpresa;
        this.idSocioComercial = idSocioComercial;
        this.numeroOc = numeroOc;
        this.total = total;
        this.tipoMoneda = tipoMoneda;
        this.tipoCambio = tipoCambio;
        this.rfcVendedor = rfcVendedor;
    }

    public Integer getIdOrdenCompra() {
        return this.idOrdenCompra;
    }

    public void setIdOrdenCompra(Integer idOrdenCompra) {
        this.idOrdenCompra = idOrdenCompra;
    }

    public int getIdEmpresa() {
        return this.idEmpresa;
    }

    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

    public Integer getIdSocioComercial() {
        return this.idSocioComercial;
    }

    public void setIdSocioComercial(Integer idSocioComercial) {
        this.idSocioComercial = idSocioComercial;
    }

    public String getNumeroOc() {
        return this.numeroOc;
    }

    public void setNumeroOc(String numeroOc) {
        this.numeroOc = numeroOc;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public String getTipoMoneda() {
        return this.tipoMoneda;
    }

    public void setTipoMoneda(String tipoMoneda) {
        this.tipoMoneda = tipoMoneda;
    }

    public BigDecimal getTipoCambio() {
        return this.tipoCambio;
    }

    public void setTipoCambio(BigDecimal tipoCambio) {
        this.tipoCambio = tipoCambio;
    }

    public String getRfcVendedor() {
        return this.rfcVendedor;
    }

    public void setRfcVendedor(String rfcVendedor) {
        this.rfcVendedor = rfcVendedor;
    }

}
