package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1



/**
 * Plantillas generated by hbm2java
 */
public class Plantillas  implements java.io.Serializable {


     private Integer idPlantillas;
     private int idEmpresa;
     private String nombre;
     private String ruta;

    public Plantillas() {
    }

    public Plantillas(int idEmpresa, String nombre, String ruta) {
       this.idEmpresa = idEmpresa;
       this.nombre = nombre;
       this.ruta = ruta;
    }
   
    public Integer getIdPlantillas() {
        return this.idPlantillas;
    }
    
    public void setIdPlantillas(Integer idPlantillas) {
        this.idPlantillas = idPlantillas;
    }
    public int getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(int idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }




}


