package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1



/**
 * RolesHasOpciones generated by hbm2java
 */
public class RolesHasOpciones  implements java.io.Serializable {


     private RolesHasOpcionesId id;

    public RolesHasOpciones() {
    }

    public RolesHasOpciones(RolesHasOpcionesId id) {
       this.id = id;
    }
   
    public RolesHasOpcionesId getId() {
        return this.id;
    }
    
    public void setId(RolesHasOpcionesId id) {
        this.id = id;
    }




}


