package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Script generated by hbm2java
 */
public class Script  implements java.io.Serializable {


     private Integer idScript;
     private String nombre;
     private String ruta;
     private boolean habilitado;
     private String ejecutar;
     private String dia;
     private String hora;
     private String minuto;
     private String segundo;
     private Date ultimaFecha;
     private Date proximaFecha;
     private String descripcion;

    public Script() {
    }

	
    public Script(String nombre, String ruta, boolean habilitado, String ejecutar) {
        this.nombre = nombre;
        this.ruta = ruta;
        this.habilitado = habilitado;
        this.ejecutar = ejecutar;
    }
    public Script(String nombre, String ruta, boolean habilitado, String ejecutar, String dia, String hora, String minuto, String segundo, Date ultimaFecha, Date proximaFecha, String descripcion) {
       this.nombre = nombre;
       this.ruta = ruta;
       this.habilitado = habilitado;
       this.ejecutar = ejecutar;
       this.dia = dia;
       this.hora = hora;
       this.minuto = minuto;
       this.segundo = segundo;
       this.ultimaFecha = ultimaFecha;
       this.proximaFecha = proximaFecha;
       this.descripcion = descripcion;
    }
   
    public Integer getIdScript() {
        return this.idScript;
    }
    
    public void setIdScript(Integer idScript) {
        this.idScript = idScript;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }
    public String getEjecutar() {
        return this.ejecutar;
    }
    
    public void setEjecutar(String ejecutar) {
        this.ejecutar = ejecutar;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public String getMinuto() {
        return this.minuto;
    }
    
    public void setMinuto(String minuto) {
        this.minuto = minuto;
    }
    public String getSegundo() {
        return this.segundo;
    }
    
    public void setSegundo(String segundo) {
        this.segundo = segundo;
    }
    public Date getUltimaFecha() {
        return this.ultimaFecha;
    }
    
    public void setUltimaFecha(Date ultimaFecha) {
        this.ultimaFecha = ultimaFecha;
    }
    public Date getProximaFecha() {
        return this.proximaFecha;
    }
    
    public void setProximaFecha(Date proximaFecha) {
        this.proximaFecha = proximaFecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


