package com.iqtb.validacion.pojo;
// Generated 12-mar-2015 19:22:00 by Hibernate Tools 4.3.1



/**
 * UsuariosHasEmpresas generated by hbm2java
 */
public class UsuariosHasEmpresas  implements java.io.Serializable {


     private UsuariosHasEmpresasId id;

    public UsuariosHasEmpresas() {
    }

    public UsuariosHasEmpresas(UsuariosHasEmpresasId id) {
       this.id = id;
    }
   
    public UsuariosHasEmpresasId getId() {
        return this.id;
    }
    
    public void setId(UsuariosHasEmpresasId id) {
        this.id = id;
    }




}


